services:
  - type: web
    name: secure-chat-app
    env: python
    rootDirectory: cyberproject/cyberproject
    autoDeploy: true
    plan: free
    healthCheckPath: /
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install --prefer-binary -r requirements.txt
    startCommand: uvicorn server.main:app --host 0.0.0.0 --port=$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_HOURS
        value: 1
      - key: AES_SECRET_KEY
        generateValue: true
      - key: AES_IV
        generateValue: true
      - key: MONGODB_URL
        sync: false
      - key: DATABASE_NAME
        value: chat_app
      - key: COLLECTION_NAME
        value: users
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: SMTP_FROM_NAME
        value: Private Chat
